/** Canonical MCP tool names. */
export const MCP_TOOL_NAME = {
	listResumes: "list_resumes",
	listResumeTags: "list_resume_tags",
	getResume: "read_resume",
	getResumeAnalysis: "get_resume_analysis",
	downloadResumePdf: "download_resume_pdf",
	createResume: "create_resume",
	importResume: "import_resume",
	duplicateResume: "duplicate_resume",
	patchResume: "apply_resume_patch",
	revertResumePatch: "revert_resume_patch",
	getResumeHistory: "get_resume_history",
	branchResumeFromAction: "branch_resume_from_action",
	updateResume: "update_resume",
	deleteResume: "delete_resume",
	lockResume: "lock_resume",
	unlockResume: "unlock_resume",
	getResumeStatistics: "get_resume_statistics",
	// Workspace tools
	listWorkspaces: "list_workspaces",
	createWorkspace: "create_workspace",
	getWorkspace: "get_workspace",
	listWorkspaceMembers: "list_workspace_members",
	inviteWorkspaceMember: "invite_workspace_member",
	listWorkspaceResumes: "list_workspace_resumes",
} as const;
